_forumSimulation/forum/entries/urls.py
from django.contrib import admin
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index')
]

_forumSimulation/forum/forum/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('interface/', include(('interface.urls', 'interface'), namespace='interface')),
    path('entries/', include('entries.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

_forumSimulation/forum/interface/urls.py
from django.contrib import admin
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'), 
    path('welcome/', views.welcome, name='welcome'),
    path('new/', views.newpost, name='newpost'),
    path('my/<int:user_id>', views.mypost, name='mypost'),
    path('edit/<int:item_id>', views.edit, name='edit'),
    path('erase/<int:item_id>', views.erase, name='erase'),
    path('post/<int:item_id>', views.post, name='post'), 
    path('erase_com/<int:comment_id>/<int:item_id>', views.erase_com, name='erase_com')
]

_forumSimulation/forum/entries/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings

class Posts(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=100, verbose_name='Título: ')
    text = models.TextField(verbose_name='Texto: ')
    countLike = models.IntegerField(verbose_name='Likes', default=0)
    countUnlike = models.IntegerField(verbose_name='Unlike', default=0)
    created_at = models.DateTimeField(verbose_name='Data de Criação', auto_now_add=True)

    def __str__(self):
        return f"{ self.title }"

class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Posts, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(verbose_name='Data de Criação', auto_now_add=True)

    def __str__(self):
        return f"Comment in post {self.post}"
    

_forumSimulation/forum/interface/models.py
from django.db import models

# Create your models here.

_forumSimulation/forum/entries/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'entries/index.html')

_forumSimulation/forum/interface/views.py
from django.shortcuts import render, HttpResponseRedirect, redirect
from django.contrib.auth import authenticate, login, logout

from entries.models import *

def index(request):

    return HttpResponseRedirect('/accounts/login')

def logout(requet):
    logout(request)

def welcome(request):
    list_post = Posts.objects.all()
    return render(request, 'interface/welcome.html', {
        'list_post':list_post
    })

def mypost(request, user_id):
    list_post = Posts.objects.filter(user=user_id)
    return render(request, 'interface/manange.html', {
        'list_post':list_post
    })

def newpost(request):
    if request.method == 'GET':
        return render(request, 'interface/newpost.html')
    else:
        title = request.POST['title']
        text = request.POST['text']
        user = User.objects.get(id=request.POST['userid'])

        npost = Posts(user=user, title=title, text=text)
        npost.save()

        return redirect('interface:welcome')

def edit(request, item_id):
    item = Posts.objects.get(id=item_id)
    if request.method == 'GET':
        return render(request, 'interface/edit.html', {
            'item':item
        })
    else:
        item.title = request.POST['title']
        item.text = request.POST['text']

        item.save()

        return redirect('interface:welcome')

def erase(request, item_id):
    Posts.objects.filter(id=item_id).delete()
    return redirect('interface:welcome')

def erase_com(request, comment_id, item_id):
    Comment.objects.get(id=comment_id).delete()
    return redirect('interface:post', item_id )

def post(request, item_id):
    item = Posts.objects.get(id=item_id)
    if request.method == 'GET':
        
        comment = Comment.objects.filter(post=item_id)
        return render(request, 'interface/view.html', {
            'item': item,
            'comment':comment
        })

    else:

       text_comment = request.POST['comment']
       new_comment = Comment(user=request.user, text=text_comment, post=item )
       new_comment.save()
       comment = Comment.objects.filter(post=item_id)
       return render(request, 'interface/view.html', {
           'item':item,
           'comment':comment
       })

_forumSimulation/forum/entries/templates/entries/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Entries</title>
</head>
<body>
    
    <h4>Hello World! </h4>
    <p>Entries page.</p>

</body>
</html>

_forumSimulation/forum/interface/templates/interface/edit.html
{% extends "interface/layout.html" %}

{% block title %}
    Edit post
{% endblock %}

{% block body %}
    <h2>Edit post</h2>  

    <form action='' method="post">

        {% csrf_token %}
        <input type="hidden" value="{{ user.id }}" name="userid">
        <div class="form group">
            <label>Title: </label>
            <input class="form-control" type="text" name="title" value="{{ item.title }}" maxlength="100">
        </div>
        <div class="form-group">
            <label>Text: </label>
            <textarea class="form-control" name="text" rows="5">{{ item.text }}</textarea>
        </div>

        <button type="submit" class="btn btn-dark btn-sm">Submit</button>
        <a href="{% url 'interface:welcome' %}"><button type="button" class="btn btn-outline-danger btn-sm">Return</button></a>
    </form>

    

{% endblock %}

_forumSimulation/forum/interface/templates/interface/error.html
<h4>You do not have access for this page. Please, Log in.</h4>
<a href="{% url 'interface:index' %}">Log in</a>

_forumSimulation/forum/interface/templates/interface/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Interface</title>
    <link rel='stylesheet' href='{% static "interface/style.css" %}'>
    

</head>
<body>
    
    {% if user.is_authenticated %}
        <h4>Welcome {{ user }} </h4>
    {% else %}
        <h4>You do not have access for this page. Please, Log in.</h4>
    {% endif %}

</body>
</html>

_forumSimulation/forum/interface/templates/interface/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link href="../../static/interface/style.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@400;500;600&display=swap" rel="stylesheet">
    <title>{% block title %}{% endblock %}</title>

</head>
<body>

    <nav class="navbar navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'interface:welcome' %}">
            <img src="{% static 'img/logo.svg' %}" width="30" height="30" class="d-inline-block align-top" alt="" loading="lazy"> Fórum
        </a>       
    </nav>

{% block body %}{% endblock %}

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    
</body>
</html>

_forumSimulation/forum/interface/templates/interface/manange.html
{% extends "interface/layout.html" %}

{% block title %}
    Manange posts
{% endblock %}

{% block body %}

    <div class="container">
        {% if user.is_authenticated %}

            <h2>Manange page.</h2>

            {% if list_post %}
            <table class="table">
                <tr>
                    <th scope="col">Nº</th>
                    <th scope="col">User</th>
                    <th scope="col">Title</th>
                    <th scope="col">Created at</th>
                </tr>
                {% for item in list_post %}
                    <tr>
                        <th>{{ item.id }}</th>
                        <th>{{ item.user }}</th>
                        <th>{{ item.title }}</th>
                        <th>{{ item.created_at }}</th>
                        <th><a style="text-decoration: none;" href="{% url 'interface:edit' item.id %}"><img class="img-edit" src="../../static/img/edit.svg" alt="">&nbsp; Edit</a></th>
                        <th><a style="text-decoration: none;" href="{% url 'interface:erase' item.id %}"><img class='img-edit' src="../../static/img/clean.svg" alt=""> Erase</a></th>
                    </tr>
                {% endfor %}
                        
                
            </table>

                


            {% else %}

            {% endif %}
        
        {% else %}

            <p> User is not authenticated</p>

        {% endif %}

        <a href="{% url 'interface:welcome' %}"><button type="button" class="btn btn-outline-secondary">Return</button></a>

    </div>

{% endblock %}

_forumSimulation/forum/interface/templates/interface/newpost.html
{% extends "interface/layout.html" %}

{% block title %}
    New post
{% endblock %}

{% block body %}

    <div class="container">
        {% if user.is_authenticated %}
            <form action='' method="post">

                {% csrf_token %}
                <input type="hidden" value="{{ user.id }}" name="userid">
                <div class="form group">
                    <label>Title: </label>
                    <input class="form-control" type="text" name="title" maxlength="100">
                </div>
                <div class="form-group">
                    <label>Text: </label>
                    <textarea class="form-control" name="text" rows="5"></textarea>
                </div>

                <button type="submit" class="btn btn-success btn-sm">Submit</button>
                <a href="{% url 'interface:welcome' %}"><button type="button" class="btn btn-outline-secondary btn-sm">Return</button></a>

            </form>

            
        {% endif %}
    </div>

{% endblock %}

_forumSimulation/forum/interface/templates/interface/view.html
{% extends 'interface/layout.html' %}

{% block title %}
    Post
{% endblock %}

{% block body %}

{% if user.is_authenticated %}
    <div class="container">
        <div class="content_view">

            <div class="title_view"><h5> {{ item.title }} </h5></div>
            <div class="text_view"> {{ item.text }} </div>   

        </div>
        
        <div class="content_comments">

            {% for com in comment %}

                <ul class="list-group list_comment">
                    <li class="list-group-item">
                        <span style="font-weight: bold;">{{ com.user }} </span> - <span style="opacity: 0.6;">Created at {{ com.created_at }}  - &nbsp;
                        {% if user.is_staff %}

                                <a href="{% url 'interface:erase_com' com.id item.id %}" style="text-decoration: none;"><img class='img-edit' src="../../static/img/clean.svg" alt="">&nbsp;Erase</a></span>
                        
                        {% endif %}
                    </li>
                    <li class="list-group-item">{{ com.text }}</li>
                    
                </ul>

            {% endfor %}

        </div>


        <form class="form_comment" action="" method="post">

            {% csrf_token %}

            <div class="form-group">
                <textarea name="comment" rows="5" class="form-control"></textarea>
            </div>

            <a href="#"><button class="btn btn-outline-success btn-sm" type="submit">Comment</button></a>
            <a href="{% url 'interface:welcome' %}"><button type="button" class="btn btn-outline-dark btn-sm">Return</button></a>

        </form>

        
    </div>
   

{% endif %}



{% endblock %}

_forumSimulation/forum/interface/templates/interface/welcome.html
{% extends "interface/layout.html" %}

{% block title %}
    Home
{% endblock %}

{% block body %}

    {% if user.is_authenticated %}

    <div class="container"> 

        <table class="table">
            <tr>
                <th scope="col">Title</th>
                <th scope="col">User</th>
                <th scope="col">Created at</th>
            </tr>

            {% if list_post %}

                {% for item in list_post %}
                    <tr>
                        
                        <td><a style="text-decoration: none;" href="{% url 'interface:post' item.id %}"> {{ item.title }} </a></td>
                        <td>{{ item.user }}</td>
                        <td>{{ item.created_at }}</td>
                    </tr>
                {% endfor %}
                    
            {% else %}

                <p>This content is empty</p>

            {% endif %}



        </table>
        <br>

        <a href="{% url 'interface:newpost'%}"><button type='button' class="btn btn-outline-primary btn-sm">New Post</button></a>
        <a href="{% url 'interface:mypost' user.id %}"><button class="btn btn-outline-primary btn-sm">Manage post</button></a>
        <a href="{% url 'logout' %}"><button class="btn btn-dark btn-sm">Logout</button></a>
        

        {% else %}
            <h4>You do not have access for this page. Please, Log in.</h4>
            <a href="{% url 'interface:index' %}">Log in</a>
        {% endif %}
    
    </div>

{% endblock %}